apiVersion: batch/v1
kind: Job
metadata:
  name: mpi-master
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: mpi-master
    spec:
      restartPolicy: Never

      dnsConfig:
        searches:
          - mpi-worker.default.svc.cluster.local
          
      containers:
        - name: mpi-master
          image: mpi-counter:latest
          imagePullPolicy: Never
          env:
            - name: "ROLE"
              value: "master" 
            - name: "N"
              value: "20"
            - name: "NP"
              value: "14"

            - name: "WORKER_HOSTS"
              value: "mpi-worker-0,mpi-worker-1,mpi-worker-2"
              
            - name: "OMPI_MCA_plm_rsh_args"
              value: "-o StrictHostKeyChecking=no"
              
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: mpi-worker
                topologyKey: "kubernetes.io/hostname"